/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked.tasks

import io.github.malczuuu.nullmarked.fixtures.TestProject
import io.github.malczuuu.nullmarked.internal.PLUGIN_VERSION
import io.github.malczuuu.nullmarked.internal.PackageRule
import java.io.File
import org.assertj.core.api.Assertions.assertThat
import org.gradle.api.Project
import org.gradle.api.provider.Provider
import org.gradle.kotlin.dsl.listProperty
import org.gradle.kotlin.dsl.register
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

class GeneratePackageInfoTest {

  @TempDir lateinit var projectDir: File

  private lateinit var project: Project
  private lateinit var testProject: TestProject
  private lateinit var sourceDir: File
  private lateinit var outputDir: File
  private lateinit var task: GeneratePackageInfo

  @BeforeEach
  fun beforeEach() {
    project = ProjectBuilder.builder().withProjectDir(projectDir).build()
    testProject = TestProject(projectDir)
    sourceDir = testProject.file("src/main/java").apply { mkdirs() }
    outputDir = testProject.file("build/generated-package-info")
    task =
        project.tasks
            .register<GeneratePackageInfo>("generatePackageInfo") {
              sourceDirectories.from(sourceDir)
              outputDirectory.set(outputDir)
            }
            .get()
  }

  private fun writeSource(relativePath: String, content: String = "class Placeholder {}") {
    testProject.writeSource(relativePath, content)
  }

  private fun generatedPackageInfo(packageName: String): File = TestProject.packageInfoUnder(outputDir, packageName)

  /** Stands in for the rules the plugin feeds the task from the `nullmarked { ... }` DSL. */
  private fun inheritedRules(vararg rules: PackageRule): Provider<List<PackageRule>> =
      project.objects.listProperty<PackageRule>().apply { set(rules.toList()) }

  @Test
  fun `generates package-info for packages containing java files`() {
    writeSource("com/acme/Foo.java")
    writeSource("com/acme/util/Util.java")

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).exists()
    assertThat(generatedPackageInfo("com.acme.util")).exists()
  }

  @Test
  fun `generated file contains @NullMarked and package declaration`() {
    writeSource("com/acme/Foo.java")

    task.generatePackageInfos()

    val content = generatedPackageInfo("com.acme").readText()
    assertThat(content)
        .contains("""Generated by NullMarked Gradle Plugin version "$PLUGIN_VERSION".""")
        .doesNotContain("unknown")
        .contains("@org.jspecify.annotations.NullMarked")
        .contains("package com.acme;")
  }

  @Test
  fun `omits the header comment when headerEnabled is false`() {
    writeSource("com/acme/Foo.java")
    task.headerEnabled.set(false)

    task.generatePackageInfos()

    val content = generatedPackageInfo("com.acme").readText()
    assertThat(content)
        .doesNotContain("Generated by")
        .isEqualTo("@org.jspecify.annotations.NullMarked\npackage com.acme;\n")
  }

  @Test
  fun `skips packages with hand-written package-info`() {
    writeSource("com/acme/Foo.java")
    writeSource("com/acme/package-info.java", "package com.acme;")

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
  }

  @Test
  fun `skips the default package`() {
    writeSource("TopLevel.java")

    task.generatePackageInfos()

    assertThat(File(outputDir, "package-info.java")).doesNotExist()
  }

  @Test
  fun `skips intermediate directories without java files`() {
    writeSource("com/acme/deep/Foo.java")

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme.deep")).exists()
    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
    assertThat(generatedPackageInfo("com")).doesNotExist()
  }

  @Test
  fun `ignores non-java files`() {
    writeSource("com/acme/notes.txt", "not java")

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
  }

  @Test
  fun `removes stale output on regeneration`() {
    writeSource("com/acme/Foo.java")
    task.generatePackageInfos()
    assertThat(generatedPackageInfo("com.acme")).exists()

    File(sourceDir, "com/acme/Foo.java").delete()
    writeSource("com/other/Bar.java")
    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
    assertThat(generatedPackageInfo("com.other")).exists()
  }

  @Test
  fun `rewrites an existing package-info when its expected content changes`() {
    writeSource("com/acme/Foo.java")
    task.generatePackageInfos()
    val before = generatedPackageInfo("com.acme").readText()
    assertThat(before).contains("Generated by")

    task.headerEnabled.set(false)
    task.generatePackageInfos()

    val after = generatedPackageInfo("com.acme").readText()
    assertThat(after).isNotEqualTo(before).doesNotContain("Generated by")
  }

  @Test
  fun `leaves an up-to-date package-info unchanged on regeneration`() {
    writeSource("com/acme/Foo.java")
    task.generatePackageInfos()
    val before = generatedPackageInfo("com.acme").readText()

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme").readText()).isEqualTo(before)
  }

  @Test
  fun `deletes previously generated output when generation is disabled`() {
    writeSource("com/acme/Foo.java")
    task.generatePackageInfos()
    assertThat(generatedPackageInfo("com.acme")).exists()

    task.generationEnabled.set(false)
    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
  }

  @Test
  fun `excludes a single package without touching its subpackages`() {
    writeSource("com/acme/Foo.java")
    writeSource("com/acme/util/Util.java")
    task.packages { exclude("com.acme") }

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
    assertThat(generatedPackageInfo("com.acme.util")).exists()
  }

  @Test
  fun `excludes a package subtree with a dot-dot pattern`() {
    writeSource("com/acme/Foo.java")
    writeSource("com/acme/util/Util.java")
    writeSource("com/other/Bar.java")
    task.packages { exclude("com.acme..") }

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
    assertThat(generatedPackageInfo("com.acme.util")).doesNotExist()
    assertThat(generatedPackageInfo("com.other")).exists()
  }

  @Test
  fun `evaluates the task's own packages block after the inherited rules`() {
    writeSource("com/acme/Foo.java")
    writeSource("com/acme/util/Util.java")
    task.inheritPackageRules(inheritedRules(PackageRule(included = false, identifier = "com.acme..")))
    task.packages { include("com.acme.util") }

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
    assertThat(generatedPackageInfo("com.acme.util")).exists()
  }

  @Test
  fun `accumulates rules of multiple packages blocks in declaration order`() {
    writeSource("com/acme/Foo.java")
    writeSource("com/acme/util/Util.java")
    task.packages { exclude("com.acme..") }
    task.packages { include("com.acme.util") }

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
    assertThat(generatedPackageInfo("com.acme.util")).exists()
  }

  @Test
  fun `leaves files other than package-info alone in the output directory`() {
    writeSource("com/acme/Foo.java")
    val stray = File(outputDir, "com/acme/Stray.java").apply { parentFile.mkdirs() }.also { it.writeText("stray") }

    task.generatePackageInfos()

    assertThat(stray).exists()
    assertThat(generatedPackageInfo("com.acme")).exists()
  }

  @Test
  fun `pruning stops at a directory still holding another package`() {
    writeSource("com/acme/one/One.java")
    writeSource("com/acme/two/Two.java")
    task.generatePackageInfos()

    task.packages { exclude("com.acme.one") }
    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme.one")).doesNotExist()
    assertThat(File(outputDir, "com/acme/one")).doesNotExist()
    assertThat(generatedPackageInfo("com.acme.two")).exists()
  }

  @Test
  fun `merges packages across multiple source directories`() {
    val secondSourceDir = File(projectDir, "src/main/java-extra").apply { mkdirs() }
    task.sourceDirectories.from(secondSourceDir)
    writeSource("com/acme/Foo.java")
    File(secondSourceDir, "com/acme/package-info.java").apply {
      parentFile.mkdirs()
      writeText("package com.acme;")
    }

    task.generatePackageInfos()

    assertThat(generatedPackageInfo("com.acme")).doesNotExist()
  }
}
