/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked

import io.github.malczuuu.nullmarked.fixtures.TestProject
import java.io.File
import org.assertj.core.api.Assertions.assertThat
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

/**
 * Exercises the whole `nullmarked { ... }` DSL from a Groovy `build.gradle`.
 *
 * The Kotlin DSL binds to the extension statically, while Groovy resolves everything at runtime through Gradle's
 * decorated classes: `Property` assignment needs a generated setter, the nested blocks need closure-to `Action`
 * coercion, and `exclude` needs Groovy's vararg dispatch. None of that is covered by the Kotlin DSL tests, so the
 * public DSL gets its own Groovy round-trip.
 */
class GroovyDslFunctionalTest {

  @TempDir lateinit var projectDir: File

  private lateinit var project: TestProject

  @BeforeEach
  fun beforeEach() {
    project = TestProject(projectDir)
    project.writeStandardGroovyBuild()
    project.writeSampleSources()
  }

  @Test
  fun `configures every dsl entry point from a groovy build script`() {
    project.writeSource(
        "com/acme/internal/Skipped.java",
        """
        package com.acme.internal;

        public class Skipped {}
        """,
    )
    project.writeTestSource(
        "com/acme/FooTest.java",
        """
        package com.acme;

        class FooTest {}
        """,
    )
    project.appendToGroovyBuildScript(
        """
        nullmarked {
            enabled = true
            headerEnabled = false
            verifyOnly = false
            jspecifyVersion = '1.0.0'
            packages {
                exclude '..internal..'
            }
            sourceSet('test') {
                enabled = false
            }
        }
        """
    )

    val result = project.runner("compileJava", "compileTestJava").build()

    assertThat(result.task(":generatePackageInfo")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(result.task(":compileJava")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(project.generatedPackageInfo("com.acme")).exists()
    assertThat(project.generatedPackageInfo("com.acme.internal")).doesNotExist()
    assertThat(project.generatedPackageInfo("com.acme", sourceSet = "test")).doesNotExist()
    assertThat(project.generatedPackageInfo("com.acme").readText()).doesNotContain("Generated by")
  }

  @Test
  fun `configures task package rules from a groovy build script`() {
    project.appendToGroovyBuildScript(
        """
        tasks.withType(io.github.malczuuu.nullmarked.tasks.GeneratePackageInfo).configureEach {
            packages {
                exclude 'com.acme..'
            }
        }
        """
    )

    val result = project.runner("generatePackageInfo").build()

    assertThat(result.task(":generatePackageInfo")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(project.generatedPackageInfo("com.acme")).doesNotExist()
  }

  @Test
  fun `reports an invalid package identifier from a groovy build script`() {
    project.appendToGroovyBuildScript(
        """
        nullmarked {
            packages {
                exclude 'com.acme!!'
            }
        }
        """
    )

    val result = project.runner("generatePackageInfo").buildAndFail()

    assertThat(result.output).contains("Invalid package identifier 'com.acme!!'")
  }
}
