/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked

import io.github.malczuuu.nullmarked.fixtures.TestProject
import java.io.File
import org.assertj.core.api.Assertions.assertThat
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

/**
 * Runs the core plugin scenario, from a Groovy `build.gradle`, against the Gradle version given by the
 * `compat.gradle.version` system property (`-Pcompat.gradle.version=...` on the build; the CI workflow supplies it from
 * its version matrix). Without the property, the current TestKit Gradle version is used. Run via the `integrationTest`
 * suite. Mirrors [KotlinDslCompatibilityTest] test-for-test, one per DSL.
 */
class GroovyDslCompatibilityTest {

  @TempDir lateinit var projectDir: File

  private val gradleVersion: String? = System.getProperty("compat.gradle.version")

  @Test
  fun `configures every dsl feature, generates package-info, adds dependency and compiles`() {
    val project = TestProject(projectDir)
    project.writeStandardGroovyBuild(rootProjectName = "compat-under-test")
    project.writeFeatureCoverageSources()
    project.appendToGroovyBuildScript(
        """
        nullmarked {
            headerEnabled = false
            jspecifyVersion = '0.3.0'
            packages {
                exclude '..internal..'
                include 'com.acme.internal.reincluded'
            }
            verify {
                strict()
            }
            sourceSet('test') {
                enabled = false
            }
        }

        tasks.withType(io.github.malczuuu.nullmarked.tasks.GeneratePackageInfo).configureEach {
            packages {
                exclude 'com.acme.taskexcluded..'
            }
        }

        tasks.withType(io.github.malczuuu.nullmarked.tasks.VerifyPackageInfo).configureEach {
            packages {
                exclude 'com.acme.taskexcluded..'
            }
        }
        """
    )

    val runner = project.runner("compileJava", "compileTestJava")
    gradleVersion?.let(runner::withGradleVersion)
    val result = runner.build()

    assertThat(result.task(":generatePackageInfo")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(result.task(":verifyPackageInfo")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(result.task(":compileJava")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(result.task(":compileTestJava")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
    assertThat(project.generatedPackageInfo("com.acme")).exists()
    assertThat(project.generatedPackageInfo("com.acme").readText()).doesNotContain("Generated by")
    assertThat(project.generatedPackageInfo("com.acme.manual")).doesNotExist()
    assertThat(project.generatedPackageInfo("com.acme.internal")).doesNotExist()
    assertThat(project.generatedPackageInfo("com.acme.internal.reincluded")).exists()
    assertThat(project.generatedPackageInfo("com.acme.taskexcluded")).doesNotExist()
    assertThat(project.generatedPackageInfo("com.acme", sourceSet = "test")).doesNotExist()
    assertThat(project.compiledClass("com.acme.package-info")).exists()
  }

  @Test
  fun `verifyOnly skips generation and fails on a package without package-info`() {
    val project = TestProject(projectDir)
    project.writeStandardGroovyBuild(rootProjectName = "compat-under-test")
    project.writeSampleSources()
    project.appendToGroovyBuildScript(
        """
        nullmarked {
            verifyOnly = true
        }
        """
    )

    val runner = project.runner("compileJava")
    gradleVersion?.let(runner::withGradleVersion)
    val result = runner.buildAndFail()

    assertThat(result.task(":verifyPackageInfo")?.outcome).isEqualTo(TaskOutcome.FAILED)
    assertThat(result.output)
        .contains("1 package(s) with a package-info.java problem")
        .contains("com.acme: missing package-info.java")
    assertThat(project.generatedPackageInfo("com.acme")).doesNotExist()
  }
}
