/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked.dsl

import io.github.malczuuu.nullmarked.internal.PackageRule
import io.github.malczuuu.nullmarked.internal.VerificationMode
import javax.inject.Inject
import org.gradle.api.Action
import org.gradle.api.NamedDomainObjectContainer
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.kotlin.dsl.newInstance

/**
 * Configuration for the NullMarked plugin, available in build scripts as `nullmarked { ... }`.
 *
 * @param objects factory creating the top-level `packages { ... }` block and the [sourceSets] container
 */
abstract class NullMarkedExtension @Inject constructor(objects: ObjectFactory) {

  /**
   * Whether the plugin does anything at all. With `true`, `package-info.java` files annotated with `@NullMarked` are
   * generated for non-empty packages that do not declare one. With `false` the plugin is inert: nothing is generated,
   * nothing is verified and no JSpecify dependency is added, which is also the only way to opt out of that dependency
   * short of declaring one yourself. Defaults to `true`.
   */
  abstract val enabled: Property<Boolean>

  /** Whether generated `package-info.java` files start with a `Generated by ...` comment. Defaults to `true`. */
  abstract val headerEnabled: Property<Boolean>

  /**
   * Whether packages are only verified to declare a `package-info.java` instead of having missing ones generated. With
   * `true`, nothing is generated and the build fails on any package without a hand-written `package-info.java`.
   * Verification runs in both modes, but only fails in this one. Ignored when [enabled] is `false`, which turns both
   * generation and verification off. Defaults to `false`.
   */
  abstract val verifyOnly: Property<Boolean>

  private val packagesSpec: NullMarkedPackagesSpec = objects.newInstance()

  /** Top-level package rules in declaration order, see [NullMarkedPackagesSpec]. */
  internal val packageRules: Provider<List<PackageRule>> = packagesSpec.rules

  private val verifySpec: NullMarkedVerifySpec = objects.newInstance()

  /** Top-level `package-info.java` verification strictness, see [NullMarkedVerifySpec]. Defaults to lenient. */
  internal val verificationMode: Property<VerificationMode> = verifySpec.mode

  /**
   * Version of `org.jspecify:jspecify`, or a full `group:name:version` dependency notation (e.g. to use a fork), added
   * as a `compileOnly` dependency when the build script does not declare JSpecify itself. Defaults to `"1.0.1"`.
   */
  abstract val jspecifyVersion: Property<String>

  /**
   * Per-`SourceSet` overrides, keyed by source set name. The `main` source set is always present, even if never
   * configured explicitly. Each element's [NullMarkedSourceSetSpec.enabled], [NullMarkedSourceSetSpec.headerEnabled]
   * and [NullMarkedSourceSetSpec.verifyOnly] default to this extension's own values of the same name, and its `packages
   * { ... }` rules are evaluated after the top-level ones.
   */
  internal val sourceSets: NamedDomainObjectContainer<NullMarkedSourceSetSpec> =
      objects.domainObjectContainer(NullMarkedSourceSetSpec::class.java) { name ->
        objects.newInstance<NullMarkedSourceSetSpec>(name)
      }

  init {
    sourceSets.all {
      enabled.convention(this@NullMarkedExtension.enabled)
      headerEnabled.convention(this@NullMarkedExtension.headerEnabled)
      verifyOnly.convention(this@NullMarkedExtension.verifyOnly)
      // Adding the top-level rules while the spec is still empty puts them first, whatever order the build script
      // declares the blocks in.
      inheritPackageRules(this@NullMarkedExtension.packageRules)
      inheritVerificationMode(this@NullMarkedExtension.verificationMode)
    }
  }

  /**
   * Configures which packages the plugin processes, see [NullMarkedPackagesSpec]:
   * ```
   * nullmarked {
   *     packages {
   *         exclude("..internal..")
   *     }
   * }
   * ```
   *
   * Rules of every block accumulate, in declaration order.
   *
   * @param configuration action applied to the package rules
   */
  fun packages(configuration: Action<in NullMarkedPackagesSpec>) {
    configuration.execute(packagesSpec)
  }

  /**
   * Configures top-level `package-info.java` verification strictness, see [NullMarkedVerifySpec]:
   * ```
   * nullmarked {
   *     verify {
   *         strict()
   *     }
   * }
   * ```
   *
   * @param configuration action applied to the verification mode
   */
  fun verify(configuration: Action<in NullMarkedVerifySpec>) {
    configuration.execute(verifySpec)
  }

  /**
   * Opts the source set named [name] into `nullmarked` processing, creating its [NullMarkedSourceSetSpec] (with
   * defaults inherited from this extension's top-level properties) if it isn't already present:
   * ```
   * nullmarked {
   *     sourceSet("main21")
   * }
   * ```
   *
   * @param name name of the Gradle `SourceSet` to opt in, e.g. `"main21"`
   */
  fun sourceSet(name: String) {
    sourceSets.maybeCreate(name)
  }

  /**
   * Configures the [NullMarkedSourceSetSpec] for the source set named [name], creating it (with defaults inherited from
   * this extension's top-level properties) if it isn't already present:
   * ```
   * nullmarked {
   *     sourceSet("test") {
   *         verifyOnly = true
   *         packages {
   *             exclude("..fixtures..")
   *         }
   *     }
   * }
   * ```
   *
   * @param name name of the Gradle `SourceSet` to configure, e.g. `"main"` or `"test"`
   * @param configuration action applied to the source set's spec
   */
  fun sourceSet(name: String, configuration: Action<in NullMarkedSourceSetSpec>) {
    configuration.execute(sourceSets.maybeCreate(name))
  }
}
