/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked.dsl

import io.github.malczuuu.nullmarked.internal.PackageRule
import io.github.malczuuu.nullmarked.internal.VerificationMode
import javax.inject.Inject
import org.gradle.api.Action
import org.gradle.api.Named
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.kotlin.dsl.newInstance

/**
 * Per-`SourceSet` overrides configured via `nullmarked { sourceSet("test") { ... } }`. Each property defaults to the
 * [NullMarkedExtension] top-level value of the same name; setting it here overrides only that source set.
 *
 * @param name name of the Gradle `SourceSet` this spec configures, e.g. `"main"` or `"test"`
 * @param objects factory creating this spec's own `packages { ... }` block
 */
abstract class NullMarkedSourceSetSpec @Inject constructor(private val name: String, objects: ObjectFactory) : Named {

  /**
   * Whether the plugin does anything for this source set, see [NullMarkedExtension.enabled]. With `false` it is inert
   * here: no generation, no verification and no JSpecify dependency. Defaults to `nullmarked.enabled`.
   */
  abstract val enabled: Property<Boolean>

  /**
   * Whether generated `package-info.java` files for this source set start with a `Generated by ...` comment. Defaults
   * to `nullmarked.headerEnabled`.
   */
  abstract val headerEnabled: Property<Boolean>

  /**
   * Whether packages of this source set are only verified to declare a `package-info.java` instead of having missing
   * ones generated, see [NullMarkedExtension.verifyOnly]. Defaults to `nullmarked.verifyOnly`.
   */
  abstract val verifyOnly: Property<Boolean>

  private val packagesSpec: NullMarkedPackagesSpec = objects.newInstance()

  /** Package rules of this source set in declaration order, top-level ones first. */
  internal val packageRules: Provider<List<PackageRule>> = packagesSpec.rules

  private val verifySpec: NullMarkedVerifySpec = objects.newInstance()

  /**
   * `package-info.java` verification strictness of this source set, see [NullMarkedExtension.verificationMode].
   * Defaults to `nullmarked.verify`.
   */
  internal val verificationMode: Property<VerificationMode> = verifySpec.mode

  /** @return name of the Gradle `SourceSet` this spec configures */
  override fun getName(): String = name

  /**
   * Configures which packages the plugin processes for this source set, see [NullMarkedPackagesSpec]. These rules are
   * evaluated after the top-level `nullmarked { packages { ... } }` ones, so they can re-include what those excluded.
   *
   * @param configuration action applied to the package rules
   */
  fun packages(configuration: Action<in NullMarkedPackagesSpec>) {
    configuration.execute(packagesSpec)
  }

  /**
   * Configures `package-info.java` verification strictness for this source set, see [NullMarkedVerifySpec]. Defaults to
   * `nullmarked.verify` unless overridden here.
   *
   * @param configuration action applied to the verification mode
   */
  fun verify(configuration: Action<in NullMarkedVerifySpec>) {
    configuration.execute(verifySpec)
  }

  /**
   * Adds the top-level rules ahead of this source set's own ones. Called by [NullMarkedExtension] right after this spec
   * is created, while it is still empty, so that source set rules always come last however the build script orders the
   * blocks.
   *
   * @param rules top-level package rules
   */
  internal fun inheritPackageRules(rules: Provider<List<PackageRule>>) {
    packagesSpec.rules.addAll(rules)
  }

  /**
   * Defaults this source set's verification mode to the top-level one. Called by [NullMarkedExtension] right after this
   * spec is created; a later [verify] call on this spec always overrides it, whatever order the build script declares
   * the blocks in.
   *
   * @param mode top-level verification mode
   */
  internal fun inheritVerificationMode(mode: Provider<VerificationMode>) {
    verifySpec.mode.convention(mode)
  }
}
