/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.IgnoreEmptyDirectories
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.SkipWhenEmpty
import org.gradle.api.tasks.TaskAction

/**
 * Scans the hand-written Java source directories of a source set and generates a `package-info.java` annotated with
 * `org.jspecify.annotations.NullMarked` for every package that contains at least one Java file but no
 * `package-info.java` of its own. When [generationEnabled] is `false`, only deletes previously generated output.
 *
 * Generation is incremental: on each run, only packages whose expected content changed are (re)written and only stale
 * output (for packages that no longer need generation) is pruned, rather than wiping and regenerating the whole output
 * directory.
 *
 * The task is cacheable. [sourceDirectories] are tracked with relative path sensitivity, so entries stay valid across
 * checkout locations, and a cache hit restores the whole [outputDirectory] instead of running the reconciliation above.
 * Upgrading the plugin invalidates entries as well: the version stamped into the header comes from the task's own
 * classpath, which Gradle folds into the cache key. With no source directory to scan the task is skipped as `NO-SOURCE`
 * and its previous output is removed.
 */
@CacheableTask
abstract class GeneratePackageInfoTask : DefaultTask() {

  init {
    generationEnabled.convention(true)
    headerEnabled.convention(true)
    packageSelectionRules.convention(emptyList())
  }

  /** Whether generation is enabled. When `false`, the task deletes previously generated output instead. */
  @get:Input abstract val generationEnabled: Property<Boolean>

  /** Whether the generated files start with a `Generated by ...` comment. */
  @get:Input abstract val headerEnabled: Property<Boolean>

  /**
   * Ordered package rules deciding which packages are generated for. Each entry is a package identifier (ArchUnit
   * syntax, see [PackagePattern]) prefixed with `-` to exclude or `+` to include it, e.g. `-com.acme..` or
   * `+com.acme.api`. Order matters: the last rule matching a package wins, and a package no rule matches is generated
   * for.
   *
   * Configure these through the `nullmarked { packages { ... } }` block, see [NullMarkedPackagesSpec], rather than
   * setting them here. The input takes plain strings on purpose: the rules are modeled internally by
   * [PackageRule.encode], and keeping that type out of a public task property keeps the plugin's public API free of
   * internals and spares build scripts from importing plugin types to configure a task.
   */
  @get:Input abstract val packageSelectionRules: ListProperty<String>

  /** Hand-written Java source directories to scan (the generated output directory is excluded). */
  @get:InputFiles
  @get:SkipWhenEmpty
  @get:IgnoreEmptyDirectories
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  /** Directory the generated `package-info.java` files are written to. */
  @get:OutputDirectory abstract val outputDirectory: DirectoryProperty

  /**
   * Incrementally reconciles [outputDirectory] with what [sourceDirectories] currently require: writes only new or
   * changed `package-info.java` files and prunes only those that are no longer needed, leaving up-to-date files
   * untouched.
   */
  @TaskAction
  fun generatePackageInfos() {
    val outputDir = outputDirectory.get().asFile
    outputDir.mkdirs()

    val expectedContents = findAllExpectedPackageInfos()

    val existingFiles = findExistingPackageInfos(outputDir)

    prunePackages(existingFiles, expectedContents, outputDir)

    expectedContents.forEach { (packageName, content) ->
      ensurePackageInfoFile(existingFiles, packageName, outputDir, content)
    }
  }

  private fun findAllExpectedPackageInfos(): Map<String, String> =
      if (generationEnabled.get()) {
        computeExpectedPackageInfos(
            sourceDirectories.files,
            packageSelectionRules.get(),
            headerEnabled.get(),
            PLUGIN_VERSION,
        )
      } else {
        emptyMap()
      }
}
