/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked.internal

import java.io.File

/**
 * Computes the `package-info.java` content each package needing generation should have.
 *
 * @param sourceDirectories hand-written Java source directories to scan
 * @param packageRules ordered package rules, as encoded by [PackageRule.encode]
 * @param headerEnabled whether the content starts with a `Generated by ...` comment
 * @param pluginVersion plugin version stamped into the header comment
 * @return package name mapped to the `package-info.java` content it should have
 */
internal fun computeExpectedPackageInfos(
    sourceDirectories: Iterable<File>,
    packageRules: List<String>,
    headerEnabled: Boolean,
    pluginVersion: String,
): Map<String, String> {
  val header = preparePackageInfoHeader(headerEnabled, pluginVersion)
  return findPackagesWithoutPackageInfo(sourceDirectories, packageRules).associateWith { packageName ->
    header +
        """
        @org.jspecify.annotations.NullMarked
        package $packageName;
        """
            .trimIndent() +
        "\n"
  }
}

/**
 * Finds packages that contain at least one `.java` file, have no `package-info.java` of their own, and are processed
 * according to [packageRules]. Used to decide what [io.github.malczuuu.nullmarked.tasks.GeneratePackageInfo] generates,
 * and shares its directory scan with [findPackageInfoViolations].
 *
 * @param sourceDirectories Java source directories to scan
 * @param packageRules ordered package rules, as encoded by [PackageRule.encode]
 * @return package names lacking a `package-info.java`
 */
internal fun findPackagesWithoutPackageInfo(
    sourceDirectories: Iterable<File>,
    packageRules: List<String>,
): Set<String> {
  val scan = scanPackageInfoState(sourceDirectories)
  val filter = PackageFilter(packageRules)
  return (scan.packagesWithJavaFiles - scan.packageInfoFiles.keys).filterNot { filter.isExcluded(it) }.toSortedSet()
}

/**
 * Finds every `package-info.java` problem among packages that contain at least one `.java` file and are processed
 * according to [packageRules], judged by [mode]: [VerificationMode.LENIENT] only checks presence, while
 * [VerificationMode.EXPLICIT] and [VerificationMode.STRICT] also inspect content for `@NullMarked`/`@NullUnmarked`.
 *
 * @param sourceDirectories Java source directories to scan
 * @param packageRules ordered package rules, as encoded by [PackageRule.encode]
 * @param mode verification strictness
 * @return violations found, one per offending package, in package name order
 */
internal fun findPackageInfoViolations(
    sourceDirectories: Iterable<File>,
    packageRules: List<String>,
    mode: VerificationMode,
): List<PackageInfoViolation> {
  val scan = scanPackageInfoState(sourceDirectories)
  val filter = PackageFilter(packageRules)
  return scan.packagesWithJavaFiles
      .filterNot { filter.isExcluded(it) }
      .mapNotNull { packageName -> classifyPackageInfo(packageName, scan.packageInfoFiles[packageName], mode) }
}

/**
 * Finds every previously generated `package-info.java` under [outputDir].
 *
 * @param outputDir directory the generated `package-info.java` files are written to
 * @return package name mapped to its `package-info.java` file
 */
internal fun findExistingPackageInfos(outputDir: File): Map<String, File> {
  return outputDir
      .walkTopDown()
      .filter { it.isFile && it.name == "package-info.java" }
      .associateBy { findPackageNameOf(outputDir, it) }
}

/**
 * Deletes generated `package-info.java` files that are no longer needed, pruning empty parent directories left behind
 * up to (but excluding) [outputDir].
 *
 * @param existingFiles previously generated files, as returned by [findExistingPackageInfos]
 * @param expectedContents package name mapped to the content it should currently have; packages missing from this map
 *   are considered stale
 * @param outputDir directory the generated `package-info.java` files are written to
 */
internal fun prunePackages(
    existingFiles: Map<String, File>,
    expectedContents: Map<String, String>,
    outputDir: File,
) {
  val filesToPrune = existingFiles.keys.filter { it !in expectedContents }
  filesToPrune.forEach { packageName -> prunePackage(existingFiles.getValue(packageName), outputDir) }
}

/**
 * Writes [content] for [packageName] if no `package-info.java` exists for it yet, or rewrites it if the existing one
 * doesn't already match [content]. Leaves an up-to-date file untouched.
 *
 * @param existingFiles previously generated files, as returned by [findExistingPackageInfos]
 * @param packageName package the `package-info.java` belongs to
 * @param outputDir directory the generated `package-info.java` files are written to
 * @param content `package-info.java` content [packageName] should have
 */
internal fun ensurePackageInfoFile(
    existingFiles: Map<String, File>,
    packageName: String,
    outputDir: File,
    content: String,
) {
  val existingFile = existingFiles[packageName]
  if (existingFile == null) {
    writeNewPackageInfo(outputDir, packageName, content)
  } else if (existingFile.isPackageInfoDirty(content)) {
    existingFile.rewritePackageInfo(content)
  }
}

/**
 * Result of walking a set of source directories once: which packages have at least one hand-written `.java` file (other
 * than `package-info.java`), and the `package-info.java` file each package has, if any.
 */
private data class PackageInfoScan(val packagesWithJavaFiles: Set<String>, val packageInfoFiles: Map<String, File>)

private fun scanPackageInfoState(sourceDirectories: Iterable<File>): PackageInfoScan {
  val packagesWithJavaFiles = sortedSetOf<String>()
  val packageInfoFiles = sortedMapOf<String, File>()

  sourceDirectories
      .filter { it.isDirectory }
      .forEach { sourceDir ->
        sourceDir
            .walkTopDown()
            .filter { it.isFile && it.extension == "java" }
            .forEach { file ->
              val packageName = findPackageNameOf(sourceDir, file)
              if (file.name == "package-info.java") {
                packageInfoFiles[packageName] = file
              } else if (packageName.isNotEmpty()) {
                packagesWithJavaFiles += packageName
              }
            }
      }

  return PackageInfoScan(packagesWithJavaFiles, packageInfoFiles)
}

/**
 * Judges a single package's `package-info.java` (or lack of one) against [mode].
 *
 * @return the violation found, or `null` if the package satisfies [mode]
 */
private fun classifyPackageInfo(
    packageName: String,
    packageInfoFile: File?,
    mode: VerificationMode,
): PackageInfoViolation? {
  if (packageInfoFile == null) {
    return PackageInfoViolation.Missing(packageName)
  }
  if (mode == VerificationMode.LENIENT) {
    return null
  }

  val content = stripComments(packageInfoFile.readText())
  val hasNullMarked = NULL_MARKED_ANNOTATION_REGEX.containsMatchIn(content)
  val hasNullUnmarked = NULL_UNMARKED_ANNOTATION_REGEX.containsMatchIn(content)

  return when {
    hasNullMarked && hasNullUnmarked -> PackageInfoViolation.Conflicting(packageName)
    hasNullMarked -> null
    hasNullUnmarked -> if (mode == VerificationMode.STRICT) PackageInfoViolation.NotNullMarked(packageName) else null
    else -> PackageInfoViolation.Bare(packageName)
  }
}

// Strips block and line comments so a `package-info.java` merely mentioning an annotation in prose (e.g. a Javadoc
// explaining why the package is left bare) is not mistaken for the annotation actually being applied.
private fun stripComments(content: String): String =
    content.replace(BLOCK_COMMENT_REGEX, "").replace(LINE_COMMENT_REGEX, "")

private val BLOCK_COMMENT_REGEX = Regex("""/\*.*?\*/""", RegexOption.DOT_MATCHES_ALL)
private val LINE_COMMENT_REGEX = Regex("""//[^\n]*""")

// Matches both the simple annotation name and any dotted-qualified form (e.g. org.jspecify.annotations.NullMarked),
// without resolving imports: a lightweight text scan rather than a full Java parse.
private val NULL_MARKED_ANNOTATION_REGEX = Regex("""@(?:[\w.]+\.)?NullMarked\b""")
private val NULL_UNMARKED_ANNOTATION_REGEX = Regex("""@(?:[\w.]+\.)?NullUnmarked\b""")

private fun preparePackageInfoHeader(headerEnabled: Boolean, pluginVersion: String): String =
    if (headerEnabled) {
      """
        //
        // Generated by NullMarked Gradle Plugin version "$pluginVersion".
        //
        """
          .trimIndent() + "\n\n"
    } else {
      ""
    }

private fun findPackageNameOf(sourceRoot: File, javaFile: File): String {
  val parent = javaFile.parentFile
  if (parent == null || parent == sourceRoot) {
    return ""
  }
  return parent.relativeTo(sourceRoot).path.replace(File.separatorChar, '.')
}

private fun prunePackage(file: File, outputDir: File) {
  file.delete()
  var dir = file.parentFile
  while (dir != null && dir != outputDir && dir.listFiles()?.isEmpty() == true) {
    val parent = dir.parentFile
    dir.delete()
    dir = parent
  }
}

private fun writeNewPackageInfo(outputDir: File, packageName: String, content: String) {
  val packageDir = outputDir.resolve(packageName.replace('.', '/'))
  packageDir.mkdirs()
  packageDir.resolve("package-info.java").writeText(content)
}

private fun File.rewritePackageInfo(content: String) = writeText(content)

private fun File.isPackageInfoDirty(content: String): Boolean = readText() != content
