#!/bin/bash

###############################################################################
#
#   An utility script to checking which Java version compiled each submodule
#   of this project.
#
###############################################################################

echo "===================================================="
echo "Verifying Java version for classes within JAR files."
echo ""
echo "  nullmarked-gradle-plugin must be 52 (Java 8)"
echo ""
echo "Note that JAR files must exist (./gradlew build)."
echo ""

echo "===== nullmarked-gradle-plugin ===="
javap \
    -verbose \
    -classpath build/libs/nullmarked-gradle-plugin-*-SNAPSHOT.jar \
    io.github.malczuuu.nullmarked.NullMarkedPlugin \
    | grep "major version"
