/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.nullmarked.tasks

import io.github.malczuuu.nullmarked.dsl.NullMarkedPackagesSpec
import io.github.malczuuu.nullmarked.internal.PackageRule
import io.github.malczuuu.nullmarked.internal.findPackagesWithoutPackageInfo
import javax.inject.Inject
import org.gradle.api.Action
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.IgnoreEmptyDirectories
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.VerificationException
import org.gradle.kotlin.dsl.newInstance

/**
 * Verifies that every package of a source set declares a `package-info.java`, whether hand-written or generated by
 * [GeneratePackageInfo]. Fails the build listing every package that has Java files but no `package-info.java` and is
 * not excluded by [packageRules]. When [verificationEnabled] is `false`, the task passes without checking anything.
 *
 * What is verified never depends on whether generation is on: the task scans whatever [sourceDirectories] it is given,
 * so the same check covers both the generating and the `verifyOnly` setup. [verifyOnly] only shapes the failure
 * message.
 *
 * The task is cacheable, which is what [buildCacheMarker] exists for: a task declaring no output has nothing for Gradle
 * to base up-to-date checks or cache entries on. A cache hit means these exact sources already passed verification
 * elsewhere, so the check is skipped and the marker restored. Failures are never cached, so a build that fails
 * verification keeps re-running the check until the missing `package-info.java` files appear.
 *
 * @param objects factory creating this task's `packages { ... }` block
 */
@CacheableTask
abstract class VerifyPackageInfo @Inject constructor(objects: ObjectFactory) : DefaultTask() {

  init {
    verificationEnabled.convention(true)
    verifyOnly.convention(false)
  }

  /** Whether verification is performed. When `false`, the task passes unconditionally. */
  @get:Input abstract val verificationEnabled: Property<Boolean>

  /**
   * Whether the source set opted out of generated `package-info.java` files. Does not change what is verified, only how
   * a failure is explained: suggesting to turn `verifyOnly` off makes no sense when it is off already.
   */
  @get:Input abstract val verifyOnly: Property<Boolean>

  private val packagesSpec: NullMarkedPackagesSpec = objects.newInstance()

  /**
   * Ordered package rules deciding which packages are verified, read-only and in the same encoded form and for the same
   * reasons as [GeneratePackageInfo.packageRules]. Declare them through the `nullmarked { packages { ... } }` block or
   * this task's own [packages] block, see [NullMarkedPackagesSpec].
   */
  @get:Input
  val packageRules: Provider<List<String>>
    get() = packagesSpec.getEncodedRules()

  /** Java source directories to scan, including the generated one when generation is enabled. */
  @get:InputFiles
  @get:IgnoreEmptyDirectories
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  /**
   * Marker file written on success. The task produces no real artifact; the marker only gives Gradle an output to base
   * up-to-date checks and caching on.
   */
  @get:OutputFile abstract val buildCacheMarker: RegularFileProperty

  /**
   * Fails with a [VerificationException] listing every package missing a `package-info.java`, or writes
   * [buildCacheMarker] when there is nothing to report.
   */
  @TaskAction
  fun verifyPackageInfos() {
    val missingPackages = findMissingPackages()
    if (missingPackages.isNotEmpty()) {
      throw VerificationException(missingPackagesMessage(missingPackages))
    }
    writeBuildCacheMarker()
  }

  /**
   * Configures which packages this task verifies, with the same `exclude(...)` / `include(...)` API as the `nullmarked
   * { packages { ... } }` block, see [NullMarkedPackagesSpec]:
   * ```
   * tasks.withType<VerifyPackageInfo>().configureEach {
   *     packages {
   *         exclude("..generated..")
   *     }
   * }
   * ```
   *
   * These rules come after the ones inherited from the `nullmarked { ... }` DSL, so they can re-include what those
   * excluded. Rules of every block accumulate, in declaration order.
   *
   * @param configuration action applied to the package rules
   */
  fun packages(configuration: Action<in NullMarkedPackagesSpec>) {
    configuration.execute(packagesSpec)
  }

  /**
   * Adds the rules coming from the `nullmarked { ... }` DSL ahead of this task's own ones, see
   * [GeneratePackageInfo.inheritPackageRules].
   *
   * @param rules package rules of the source set this task belongs to
   */
  internal fun inheritPackageRules(rules: Provider<List<PackageRule>>) {
    packagesSpec.rules.addAll(rules)
  }

  private fun findMissingPackages(): List<String> =
      if (verificationEnabled.get()) {
        findPackagesWithoutPackageInfo(sourceDirectories.files, packageRules.get()).sorted()
      } else {
        emptyList()
      }

  private fun missingPackagesMessage(missingPackages: List<String>): String = buildString {
    append("Found ${missingPackages.size} package(s) without a package-info.java:\n")
    missingPackages.forEach { append("  - $it\n") }
    append("Add a package-info.java to each of them, or exclude them via nullmarked.packages")
    if (verifyOnly.get()) {
      append(", or let the plugin generate them by disabling nullmarked.verifyOnly")
    }
    append(".")
  }

  private fun writeBuildCacheMarker() {
    val marker = buildCacheMarker.get().asFile
    marker.parentFile.mkdirs()
    marker.writeText("OK\n")
  }
}
