/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import java.io.File
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.IgnoreEmptyDirectories
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.SkipWhenEmpty
import org.gradle.api.tasks.TaskAction

/**
 * Scans the hand-written Java source directories of a source set and generates a `package-info.java` annotated with
 * `org.jspecify.annotations.NullMarked` for every package that contains at least one Java file but no
 * `package-info.java` of its own. When [generationEnabled] is `false`, only deletes previously generated output.
 *
 * Generation is incremental: on each run, only packages whose expected content changed are (re)written and only stale
 * output (for packages that no longer need generation) is pruned, rather than wiping and regenerating the whole output
 * directory.
 */
@CacheableTask
abstract class GeneratePackageInfoTask : DefaultTask() {

  init {
    generationEnabled.convention(true)
    headerEnabled.convention(true)
    excludedPackages.convention(emptyList())
  }

  /** Whether generation is enabled. When `false`, the task deletes previously generated output instead. */
  @get:Input abstract val generationEnabled: Property<Boolean>

  /** Whether the generated files start with a `Generated by ...` comment. */
  @get:Input abstract val headerEnabled: Property<Boolean>

  /** Package identifiers (ArchUnit syntax, see [PackagePattern]) whose packages are skipped during generation. */
  @get:Input abstract val excludedPackages: ListProperty<String>

  /** Hand-written Java source directories to scan (the generated output directory is excluded). */
  @get:InputFiles
  @get:SkipWhenEmpty
  @get:IgnoreEmptyDirectories
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  /** Directory the generated `package-info.java` files are written to. */
  @get:OutputDirectory abstract val outputDirectory: DirectoryProperty

  /**
   * Incrementally reconciles [outputDirectory] with what [sourceDirectories] currently require: writes only new or
   * changed `package-info.java` files and prunes only those that are no longer needed, leaving up-to-date files
   * untouched.
   */
  @TaskAction
  fun generatePackageInfos() {
    val outputDir = outputDirectory.get().asFile
    outputDir.mkdirs()

    val expectedContents = findAllExpectedPackageInfos()

    val existingFiles = findExistingPackageInfos(outputDir)

    prunePackages(existingFiles, expectedContents, outputDir)

    expectedContents.forEach { (packageName, content) ->
      ensurePackageInfoFile(existingFiles, packageName, outputDir, content)
    }
  }

  private fun findAllExpectedPackageInfos(): Map<String, String> =
      if (generationEnabled.get()) {
        computeExpectedPackageInfos(
            sourceDirectories.files,
            excludedPackages.get(),
            headerEnabled.get(),
            PLUGIN_VERSION,
        )
      } else {
        emptyMap()
      }

  private fun prunePackages(
      existingFiles: Map<String, File>,
      expectedContents: Map<String, String>,
      outputDir: File,
  ) {
    val filesToPrune = existingFiles.keys.filter { it !in expectedContents }
    filesToPrune.forEach { packageName -> prunePackage(existingFiles.getValue(packageName), outputDir) }
  }

  private fun prunePackage(file: File, outputDir: File) {
    file.delete()
    var dir = file.parentFile
    while (dir != null && dir != outputDir && dir.listFiles()?.isEmpty() == true) {
      val parent = dir.parentFile
      dir.delete()
      dir = parent
    }
  }

  private fun ensurePackageInfoFile(
      existingFiles: Map<String, File>,
      packageName: String,
      outputDir: File,
      content: String,
  ) {
    val existingFile = existingFiles[packageName]
    if (existingFile == null) {
      writeNewPackageInfo(outputDir, packageName, content)
    } else if (existingFile.isPackageInfoDirty(content)) {
      rewritePackageInfo(existingFile, content)
    }
  }

  private fun writeNewPackageInfo(outputDir: File, packageName: String, content: String) {
    val packageDir = outputDir.resolve(packageName.replace('.', '/'))
    packageDir.mkdirs()
    packageDir.resolve("package-info.java").writeText(content)
  }

  private fun File.isPackageInfoDirty(content: String): Boolean = readText() != content

  private fun rewritePackageInfo(existingFile: File, content: String) {
    existingFile.writeText(content)
  }
}
