/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property

/** Configuration for the NullMarked plugin, available in build scripts as `nullmarked { ... }`. */
abstract class NullMarkedExtension {

  /**
   * Whether `package-info.java` files annotated with `@NullMarked` should be generated for non-empty packages that do
   * not declare one. Defaults to `true`.
   */
  abstract val enabled: Property<Boolean>

  /** Whether generated `package-info.java` files start with a `Generated by ...` comment. Defaults to `true`. */
  abstract val headerEnabled: Property<Boolean>

  /**
   * Package identifiers excluded from `package-info.java` generation, following ArchUnit's package identifier syntax:
   * `org.acme` excludes only `org.acme`, `org.acme..` excludes `org.acme` and all its subpackages, `..internal..`
   * excludes any package containing an `internal` segment, `*` matches within a single segment. Defaults to an empty
   * list.
   */
  abstract val excludedPackages: ListProperty<String>

  /**
   * Version of `org.jspecify:jspecify`, or a full `group:name:version` dependency notation (e.g. to use a fork), added
   * as a `compileOnly` dependency when the build script does not declare JSpecify itself. Defaults to `"1.0.0"`.
   */
  abstract val jspecifyVersion: Property<String>
}
