/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import java.io.File

/**
 * Finds packages that contain at least one hand-written `.java` file, have no hand-written `package-info.java` of their
 * own, and are not matched by [excludedPackages].
 *
 * @param sourceDirectories hand-written Java source directories to scan
 * @param excludedPackages package identifiers (ArchUnit syntax, see [PackagePattern]) whose packages are skipped
 * @return package names that need a generated `package-info.java`
 */
internal fun findPackagesToGenerate(sourceDirectories: Iterable<File>, excludedPackages: List<String>): Set<String> {
  val packagesToGenerate = sortedSetOf<String>()
  val packagesWithPackageInfo = sortedSetOf<String>()

  sourceDirectories.filter(File::isDirectory).forEach { sourceDir ->
    sourceDir
        .walkTopDown()
        .filter { it.isFile && it.extension == "java" }
        .forEach { file ->
          val packageName = packageNameOf(sourceDir, file)
          if (file.name == "package-info.java") {
            packagesWithPackageInfo += packageName
          } else if (packageName.isNotEmpty()) {
            packagesToGenerate += packageName
          }
        }
  }

  packagesToGenerate.removeAll(packagesWithPackageInfo)

  val excludePatterns = excludedPackages.map(PackagePattern::of)
  packagesToGenerate.removeIf { packageName -> excludePatterns.any { it.matches(packageName) } }

  return packagesToGenerate
}

/**
 * Finds every previously generated `package-info.java` under [outputDir].
 *
 * @param outputDir directory the generated `package-info.java` files are written to
 * @return package name mapped to its `package-info.java` file
 */
internal fun findExistingPackageInfos(outputDir: File): Map<String, File> {
  return outputDir
      .walkTopDown()
      .filter { it.isFile && it.name == "package-info.java" }
      .associateBy { packageNameOf(outputDir, it) }
}

/**
 * Computes the `package-info.java` content each package needing generation should have.
 *
 * @param sourceDirectories hand-written Java source directories to scan
 * @param excludedPackages package identifiers (ArchUnit syntax, see [PackagePattern]) whose packages are skipped
 * @param headerEnabled whether the content starts with a `Generated by ...` comment
 * @param pluginVersion plugin version stamped into the header comment
 * @return package name mapped to the `package-info.java` content it should have
 */
internal fun computeExpectedPackageInfos(
    sourceDirectories: Iterable<File>,
    excludedPackages: List<String>,
    headerEnabled: Boolean,
    pluginVersion: String,
): Map<String, String> {
  val header =
      if (headerEnabled) {
        """
        //
        // Generated by NullMarked Gradle Plugin version "$pluginVersion".
        //
        """
            .trimIndent() + "\n"
      } else {
        ""
      }

  return findPackagesToGenerate(sourceDirectories, excludedPackages).associateWith { packageName ->
    header +
        """
        @org.jspecify.annotations.NullMarked
        package $packageName;
        """
            .trimIndent() +
        "\n"
  }
}

/**
 * @param sourceRoot source directory [javaFile] was found under
 * @param javaFile a `.java` file located under [sourceRoot]
 * @return the dotted package name of [javaFile], or an empty string for the default package
 */
private fun packageNameOf(sourceRoot: File, javaFile: File): String {
  val parent = javaFile.parentFile
  if (parent == null || parent == sourceRoot) {
    return ""
  }
  return parent.relativeTo(sourceRoot).path.replace(File.separatorChar, '.')
}
