/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import javax.inject.Inject
import org.gradle.api.Named
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property

/**
 * Per-`SourceSet` overrides configured via `nullmarked { sourceSet("test") { ... } }`. Each property defaults to the
 * [NullMarkedExtension] top-level value of the same name; setting it here overrides only that source set.
 *
 * @param name name of the Gradle `SourceSet` this spec configures, e.g. `"main"` or `"test"`
 */
abstract class NullMarkedSourceSetSpec @Inject constructor(private val name: String) : Named {

  /** Whether `package-info.java` files are generated for this source set. Defaults to `nullmarked.enabled`. */
  abstract val enabled: Property<Boolean>

  /**
   * Whether generated `package-info.java` files for this source set start with a `Generated by ...` comment. Defaults
   * to `nullmarked.headerEnabled`.
   */
  abstract val headerEnabled: Property<Boolean>

  /**
   * Whether packages of this source set are only verified to declare a `package-info.java` instead of having missing
   * ones generated, see [NullMarkedExtension.verifyOnly]. Defaults to `nullmarked.verifyOnly`.
   */
  abstract val verifyOnly: Property<Boolean>

  /**
   * Package identifiers excluded from generation for this source set, see [NullMarkedExtension.excludedPackages].
   * Defaults to `nullmarked.excludedPackages`.
   */
  abstract val excludedPackages: ListProperty<String>

  override fun getName(): String = name
}
