/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import javax.inject.Inject
import org.gradle.api.Action
import org.gradle.api.NamedDomainObjectContainer
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.kotlin.dsl.newInstance

/** Configuration for the NullMarked plugin, available in build scripts as `nullmarked { ... }`. */
abstract class NullMarkedExtension @Inject constructor(objects: ObjectFactory) {

  /**
   * Whether `package-info.java` files annotated with `@NullMarked` should be generated for non-empty packages that do
   * not declare one. Defaults to `true`.
   */
  abstract val enabled: Property<Boolean>

  /** Whether generated `package-info.java` files start with a `Generated by ...` comment. Defaults to `true`. */
  abstract val headerEnabled: Property<Boolean>

  /**
   * Package identifiers excluded from `package-info.java` generation, following ArchUnit's package identifier syntax:
   * `org.acme` excludes only `org.acme`, `org.acme..` excludes `org.acme` and all its subpackages, `..internal..`
   * excludes any package containing an `internal` segment, `*` matches within a single segment. Defaults to an empty
   * list.
   */
  abstract val excludedPackages: ListProperty<String>

  /**
   * Version of `org.jspecify:jspecify`, or a full `group:name:version` dependency notation (e.g. to use a fork), added
   * as a `compileOnly` dependency when the build script does not declare JSpecify itself. Defaults to `"1.0.0"`.
   */
  abstract val jspecifyVersion: Property<String>

  /**
   * Per-`SourceSet` overrides, keyed by source set name. The `main` source set is always present, even if never
   * configured explicitly. Each element's [NullMarkedSourceSetSpec.enabled], [NullMarkedSourceSetSpec.headerEnabled]
   * and [NullMarkedSourceSetSpec.excludedPackages] default to this extension's own values of the same name.
   */
  val sourceSets: NamedDomainObjectContainer<NullMarkedSourceSetSpec> =
      objects.domainObjectContainer(NullMarkedSourceSetSpec::class.java) { name ->
        objects.newInstance<NullMarkedSourceSetSpec>(name)
      }

  init {
    sourceSets.all {
      enabled.convention(this@NullMarkedExtension.enabled)
      headerEnabled.convention(this@NullMarkedExtension.headerEnabled)
      excludedPackages.convention(this@NullMarkedExtension.excludedPackages)
    }
  }

  /**
   * Opts the source set named [name] into `nullmarked` processing, creating its [NullMarkedSourceSetSpec] (with
   * defaults inherited from this extension's top-level properties) if it isn't already present.
   *
   * @param name name of the Gradle `SourceSet` to opt in, e.g. `"main21"`
   */
  fun sourceSet(name: String) {
    sourceSets.maybeCreate(name)
  }

  /**
   * Configures the [NullMarkedSourceSetSpec] for the source set named [name], creating it (with defaults inherited from
   * this extension's top-level properties) if it isn't already present.
   *
   * @param name name of the Gradle `SourceSet` to configure, e.g. `"main"` or `"test"`
   * @param configuration action applied to the source set's spec
   */
  fun sourceSet(name: String, configuration: Action<in NullMarkedSourceSetSpec>) {
    configuration.execute(sourceSets.maybeCreate(name))
  }
}
