/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import java.io.File

/**
 * Computes the `package-info.java` content each package needing generation should have.
 *
 * @param sourceDirectories hand-written Java source directories to scan
 * @param excludedPackages package identifiers (ArchUnit syntax, see [PackagePattern]) whose packages are skipped
 * @param headerEnabled whether the content starts with a `Generated by ...` comment
 * @param pluginVersion plugin version stamped into the header comment
 * @return package name mapped to the `package-info.java` content it should have
 */
internal fun computeExpectedPackageInfos(
    sourceDirectories: Iterable<File>,
    excludedPackages: List<String>,
    headerEnabled: Boolean,
    pluginVersion: String,
): Map<String, String> {
  val header = generateHeader(headerEnabled, pluginVersion)
  return findPackagesToGenerate(sourceDirectories, excludedPackages).associateWith { packageName ->
    header +
        """
        @org.jspecify.annotations.NullMarked
        package $packageName;
        """
            .trimIndent() +
        "\n"
  }
}

/**
 * Finds packages that contain at least one hand-written `.java` file, have no hand-written `package-info.java` of their
 * own, and are not matched by [excludedPackages].
 *
 * @param sourceDirectories hand-written Java source directories to scan
 * @param excludedPackages package identifiers (ArchUnit syntax, see [PackagePattern]) whose packages are skipped
 * @return package names that need a generated `package-info.java`
 */
internal fun findPackagesToGenerate(sourceDirectories: Iterable<File>, excludedPackages: List<String>): Set<String> {
  val packagesToGenerate = sortedSetOf<String>()
  val packagesWithPackageInfo = sortedSetOf<String>()

  sourceDirectories
      .filter { it.isDirectory }
      .forEach { sourceDir ->
        sourceDir
            .walkTopDown()
            .filter { it.isFile && it.extension == "java" }
            .forEach { file ->
              val packageName = packageNameOf(sourceDir, file)
              if (file.name == "package-info.java") {
                packagesWithPackageInfo += packageName
              } else if (packageName.isNotEmpty()) {
                packagesToGenerate += packageName
              }
            }
      }

  packagesToGenerate.removeAll(packagesWithPackageInfo)

  val excludePatterns = excludedPackages.map { PackagePattern.of(it) }
  packagesToGenerate.removeIf { packageName -> excludePatterns.any { it.matches(packageName) } }

  return packagesToGenerate
}

/**
 * Finds every previously generated `package-info.java` under [outputDir].
 *
 * @param outputDir directory the generated `package-info.java` files are written to
 * @return package name mapped to its `package-info.java` file
 */
internal fun findExistingPackageInfos(outputDir: File): Map<String, File> {
  return outputDir
      .walkTopDown()
      .filter { it.isFile && it.name == "package-info.java" }
      .associateBy { packageNameOf(outputDir, it) }
}

/**
 * Deletes generated `package-info.java` files that are no longer needed, pruning empty parent directories left behind
 * up to (but excluding) [outputDir].
 *
 * @param existingFiles previously generated files, as returned by [findExistingPackageInfos]
 * @param expectedContents package name mapped to the content it should currently have; packages missing from this map
 *   are considered stale
 * @param outputDir directory the generated `package-info.java` files are written to
 */
internal fun prunePackages(
    existingFiles: Map<String, File>,
    expectedContents: Map<String, String>,
    outputDir: File,
) {
  val filesToPrune = existingFiles.keys.filter { it !in expectedContents }
  filesToPrune.forEach { packageName -> prunePackage(existingFiles.getValue(packageName), outputDir) }
}

/**
 * Writes [content] for [packageName] if no `package-info.java` exists for it yet, or rewrites it if the existing one
 * doesn't already match [content]. Leaves an up-to-date file untouched.
 *
 * @param existingFiles previously generated files, as returned by [findExistingPackageInfos]
 * @param packageName package the `package-info.java` belongs to
 * @param outputDir directory the generated `package-info.java` files are written to
 * @param content `package-info.java` content [packageName] should have
 */
internal fun ensurePackageInfoFile(
    existingFiles: Map<String, File>,
    packageName: String,
    outputDir: File,
    content: String,
) {
  val existingFile = existingFiles[packageName]
  if (existingFile == null) {
    writeNewPackageInfo(outputDir, packageName, content)
  } else if (existingFile.isPackageInfoDirty(content)) {
    rewritePackageInfo(existingFile, content)
  }
}

private fun generateHeader(headerEnabled: Boolean, pluginVersion: String): String =
    if (headerEnabled) {
      """
        //
        // Generated by NullMarked Gradle Plugin version "$pluginVersion".
        //
        """
          .trimIndent() + "\n\n"
    } else {
      ""
    }

private fun packageNameOf(sourceRoot: File, javaFile: File): String {
  val parent = javaFile.parentFile
  if (parent == null || parent == sourceRoot) {
    return ""
  }
  return parent.relativeTo(sourceRoot).path.replace(File.separatorChar, '.')
}

private fun prunePackage(file: File, outputDir: File) {
  file.delete()
  var dir = file.parentFile
  while (dir != null && dir != outputDir && dir.listFiles()?.isEmpty() == true) {
    val parent = dir.parentFile
    dir.delete()
    dir = parent
  }
}

private fun writeNewPackageInfo(outputDir: File, packageName: String, content: String) {
  val packageDir = outputDir.resolve(packageName.replace('.', '/'))
  packageDir.mkdirs()
  packageDir.resolve("package-info.java").writeText(content)
}

private fun rewritePackageInfo(existingFile: File, content: String) = existingFile.writeText(content)

private fun File.isPackageInfoDirty(content: String): Boolean = readText() != content
