/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.gradle.nullmarked

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.IgnoreEmptyDirectories
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.VerificationException

/**
 * Verifies that every package of a source set declares a `package-info.java`, whether hand-written or generated by
 * [GeneratePackageInfoTask]. Fails the build listing every package that has Java files but no `package-info.java` and
 * is not matched by [excludedPackages]. When [verificationEnabled] is `false`, the task passes without checking
 * anything.
 *
 * What is verified never depends on whether generation is on: the task scans whatever [sourceDirectories] it is given,
 * so the same check covers both the generating and the `verifyOnly` setup. [verifyOnly] only shapes the failure
 * message.
 */
@CacheableTask
abstract class VerifyPackageInfoTask : DefaultTask() {

  init {
    verificationEnabled.convention(true)
    verifyOnly.convention(false)
    excludedPackages.convention(emptyList())
  }

  /** Whether verification is performed. When `false`, the task passes unconditionally. */
  @get:Input abstract val verificationEnabled: Property<Boolean>

  /**
   * Whether the source set opted out of generated `package-info.java` files. Does not change what is verified, only how
   * a failure is explained: suggesting to turn `verifyOnly` off makes no sense when it is off already.
   */
  @get:Input abstract val verifyOnly: Property<Boolean>

  /** Package identifiers (ArchUnit syntax, see [PackagePattern]) whose packages are skipped during verification. */
  @get:Input abstract val excludedPackages: ListProperty<String>

  /** Java source directories to scan, including the generated one when generation is enabled. */
  @get:InputFiles
  @get:IgnoreEmptyDirectories
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  /**
   * Marker file written on success. The task produces no real artifact; the marker only gives Gradle an output to base
   * up-to-date checks and caching on.
   */
  @get:OutputFile abstract val markerFile: RegularFileProperty

  /**
   * Fails with a [VerificationException] listing every package missing a `package-info.java`, or writes [markerFile]
   * when there is nothing to report.
   */
  @TaskAction
  fun verifyPackageInfos() {
    val missingPackages = findMissingPackages()
    if (missingPackages.isNotEmpty()) {
      throw VerificationException(missingPackagesMessage(missingPackages))
    }
    writeMarker()
  }

  private fun findMissingPackages(): List<String> =
      if (verificationEnabled.get()) {
        findPackagesWithoutPackageInfo(sourceDirectories.files, excludedPackages.get()).sorted()
      } else {
        emptyList()
      }

  private fun missingPackagesMessage(missingPackages: List<String>): String = buildString {
    append("Found ${missingPackages.size} package(s) without a package-info.java:\n")
    missingPackages.forEach { append("  - $it\n") }
    append("Add a package-info.java to each of them, or exclude them via nullmarked.excludedPackages")
    if (verifyOnly.get()) {
      append(", or let the plugin generate them by disabling nullmarked.verifyOnly")
    }
    append(".")
  }

  private fun writeMarker() {
    val marker = markerFile.get().asFile
    marker.parentFile.mkdirs()
    marker.writeText("OK\n")
  }
}
